"""initial schema: core tables + sumo tables

Revision ID: 8b31956937a6
Revises: 
Create Date: 2026-07-08 12:42:56.745310

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b31956937a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required extensions (spec section 8). postgis must be installed on the
    # PostgreSQL server itself (postgis/postgis Docker image, or the native
    # Windows PostGIS bundle installed with admin rights) before this will
    # succeed -- see README "Known blockers".
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # NOTE: autogenerate emitted explicit op.create_index(..., postgresql_using='gist')
    # calls for every Geography/Geometry column below, but GeoAlchemy2's Geography
    # type defaults to spatial_index=True, which creates the identically-named GIST
    # index itself via an after_create DDL event as part of op.create_table(). Running
    # both in the same transaction fails with DuplicateTable on the second one and
    # rolls back the whole migration (confirmed against a live postgis/postgis
    # container) -- those redundant create_index/drop_index calls have been removed
    # here; the spatial indexes still exist, just created implicitly by geoalchemy2.

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel_type IN ('email','sms','whatsapp','webhook')", name='ck_alert_channels_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin','operator','viewer')", name='ck_app_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('areas_of_interest',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('center', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('bbox_min_lat', sa.Double(), nullable=False),
    sa.Column('bbox_min_lon', sa.Double(), nullable=False),
    sa.Column('bbox_max_lat', sa.Double(), nullable=False),
    sa.Column('bbox_max_lon', sa.Double(), nullable=False),
    sa.Column('polygon', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citizen_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_vision_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_status IN ('unverified','likely_valid','verified','rejected')", name='ck_citizen_reports_status'),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('expected_crowd', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('road_segments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_segment_key', sa.Text(), nullable=True),
    sa.Column('road_name', sa.Text(), nullable=True),
    sa.Column('road_class', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('length_m', sa.Double(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sumo_networks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sumo_version', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('bbox_min_lat', sa.Double(), nullable=False),
    sa.Column('bbox_min_lon', sa.Double(), nullable=False),
    sa.Column('bbox_max_lat', sa.Double(), nullable=False),
    sa.Column('bbox_max_lon', sa.Double(), nullable=False),
    sa.Column('net_file_path', sa.Text(), nullable=False),
    sa.Column('osm_file_path', sa.Text(), nullable=True),
    sa.Column('config_file_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_incidents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_incident_id', sa.Text(), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_validity', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('icon_category', sa.Integer(), nullable=True),
    sa.Column('magnitude_of_delay', sa.Integer(), nullable=True),
    sa.Column('probability_of_occurrence', sa.Text(), nullable=True),
    sa.Column('number_of_reports', sa.Integer(), nullable=True),
    sa.Column('from_text', sa.Text(), nullable=True),
    sa.Column('to_text', sa.Text(), nullable=True),
    sa.Column('road_numbers', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('length_m', sa.Double(), nullable=True),
    sa.Column('delay_sec', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_incident_id')
    )
    op.create_table('weather_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Double(), nullable=True),
    sa.Column('humidity_percent', sa.Double(), nullable=True),
    sa.Column('rainfall_mm', sa.Double(), nullable=True),
    sa.Column('wind_speed_kmph', sa.Double(), nullable=True),
    sa.Column('visibility_m', sa.Double(), nullable=True),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probe_points',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('road_segment_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('polling_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('high','medium','low')", name='ck_probe_points_priority'),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.ForeignKeyConstraint(['road_segment_id'], ['road_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sumo_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('network_id', sa.UUID(), nullable=True),
    sa.Column('sumo_edge_id', sa.Text(), nullable=False),
    sa.Column('from_node', sa.Text(), nullable=True),
    sa.Column('to_node', sa.Text(), nullable=True),
    sa.Column('road_name', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('num_lanes', sa.Integer(), nullable=True),
    sa.Column('speed_mps', sa.Double(), nullable=True),
    sa.Column('length_m', sa.Double(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['sumo_networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'sumo_edge_id')
    )
    op.create_table('sumo_scenarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('network_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('scenario_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('human_review_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("human_review_status IN ('draft','approved','rejected')", name='ck_sumo_scenarios_review_status'),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['sumo_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sumo_simulation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('baseline_run_id', sa.UUID(), nullable=True),
    sa.Column('run_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('run_dir', sa.Text(), nullable=True),
    sa.Column('sumocfg_path', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("run_type IN ('baseline','scenario')", name='ck_sumo_run_type'),
    sa.CheckConstraint("status IN ('queued','preparing','running','completed','failed','cancelled')", name='ck_sumo_run_status'),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['sumo_simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['sumo_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tomtom_sumo_edge_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('road_segment_id', sa.UUID(), nullable=True),
    sa.Column('sumo_edge_db_id', sa.UUID(), nullable=True),
    sa.Column('match_method', sa.Text(), nullable=False),
    sa.Column('distance_m', sa.Double(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('review_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('pending','approved','rejected','manual_override')", name='ck_edge_mapping_review_status'),
    sa.ForeignKeyConstraint(['road_segment_id'], ['road_segments.id'], ),
    sa.ForeignKeyConstraint(['sumo_edge_db_id'], ['sumo_edges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_anomalies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('road_segment_id', sa.UUID(), nullable=True),
    sa.Column('probe_point_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('baseline_speed_kmph', sa.Double(), nullable=True),
    sa.Column('observed_speed_kmph', sa.Double(), nullable=True),
    sa.Column('delay_sec', sa.Integer(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('low','medium','high','critical')", name='ck_anomalies_severity'),
    sa.CheckConstraint("status IN ('open','acknowledged','resolved','dismissed')", name='ck_anomalies_status'),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.ForeignKeyConstraint(['probe_point_id'], ['probe_points.id'], ),
    sa.ForeignKeyConstraint(['road_segment_id'], ['road_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_flow_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('probe_point_id', sa.UUID(), nullable=True),
    sa.Column('road_segment_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('current_speed_kmph', sa.Double(), nullable=True),
    sa.Column('free_flow_speed_kmph', sa.Double(), nullable=True),
    sa.Column('current_travel_time_sec', sa.Integer(), nullable=True),
    sa.Column('free_flow_travel_time_sec', sa.Integer(), nullable=True),
    sa.Column('speed_ratio', sa.Double(), nullable=True),
    sa.Column('delay_sec', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('road_closure', sa.Boolean(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['probe_point_id'], ['probe_points.id'], ),
    sa.ForeignKeyConstraint(['road_segment_id'], ['road_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_id', sa.UUID(), nullable=True),
    sa.Column('insight_type', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('human_review_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("human_review_status IN ('pending','approved','rejected','needs_revision')", name='ck_ai_insights_review_status'),
    sa.ForeignKeyConstraint(['anomaly_id'], ['traffic_anomalies.id'], ),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sumo_edge_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('sumo_edge_db_id', sa.UUID(), nullable=True),
    sa.Column('begin_second', sa.Integer(), nullable=True),
    sa.Column('end_second', sa.Integer(), nullable=True),
    sa.Column('mean_speed_mps', sa.Double(), nullable=True),
    sa.Column('density', sa.Double(), nullable=True),
    sa.Column('occupancy', sa.Double(), nullable=True),
    sa.Column('waiting_time_sec', sa.Double(), nullable=True),
    sa.Column('time_loss_sec', sa.Double(), nullable=True),
    sa.Column('departed', sa.Integer(), nullable=True),
    sa.Column('arrived', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['sumo_simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['sumo_edge_db_id'], ['sumo_edges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sumo_run_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('total_departed', sa.Integer(), nullable=True),
    sa.Column('total_arrived', sa.Integer(), nullable=True),
    sa.Column('total_loaded', sa.Integer(), nullable=True),
    sa.Column('completed_ratio', sa.Double(), nullable=True),
    sa.Column('average_travel_time_sec', sa.Double(), nullable=True),
    sa.Column('average_waiting_time_sec', sa.Double(), nullable=True),
    sa.Column('average_time_loss_sec', sa.Double(), nullable=True),
    sa.Column('total_time_loss_sec', sa.Double(), nullable=True),
    sa.Column('average_speed_mps', sa.Double(), nullable=True),
    sa.Column('total_teleports', sa.Integer(), nullable=True),
    sa.Column('metrics_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['sumo_simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aoi_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_id', sa.UUID(), nullable=True),
    sa.Column('ai_insight_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('draft','approved','sent','failed','cancelled')", name='ck_alerts_status'),
    sa.ForeignKeyConstraint(['ai_insight_id'], ['ai_insights.id'], ),
    sa.ForeignKeyConstraint(['anomaly_id'], ['traffic_anomalies.id'], ),
    sa.ForeignKeyConstraint(['aoi_id'], ['areas_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sumo_scenario_comparisons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('baseline_run_id', sa.UUID(), nullable=True),
    sa.Column('scenario_run_id', sa.UUID(), nullable=True),
    sa.Column('comparison_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gemini_summary_insight_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['sumo_simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['gemini_summary_insight_id'], ['ai_insights.id'], ),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['sumo_simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Additional indexes from spec sections 8 and H not emitted by
    # --- autogenerate (non-geom indexes / composite indexes) ---
    op.create_index(
        'idx_road_segments_provider_key', 'road_segments', ['provider', 'provider_segment_key']
    )
    op.create_index('idx_probe_points_active', 'probe_points', ['is_active', 'priority'])
    op.create_index(
        'idx_flow_observed_at', 'traffic_flow_observations', ['observed_at'],
        postgresql_ops={'observed_at': 'DESC'},
    )
    op.create_index(
        'idx_flow_probe_time', 'traffic_flow_observations', ['probe_point_id', 'observed_at'],
    )
    op.create_index(
        'idx_incidents_active', 'traffic_incidents', ['is_active', 'last_seen_at'],
    )
    op.create_index('idx_weather_time', 'weather_snapshots', ['observed_at'])
    op.create_index('idx_events_time', 'local_events', ['starts_at', 'ends_at'])
    op.create_index('idx_anomalies_time', 'traffic_anomalies', ['detected_at'])
    op.create_index('idx_anomalies_status', 'traffic_anomalies', ['status', 'severity'])
    op.create_index(
        'idx_ai_insights_type_time', 'ai_insights', ['insight_type', 'created_at'],
    )
    op.create_index(
        'idx_sumo_edges_network_edge', 'sumo_edges', ['network_id', 'sumo_edge_id'],
    )
    op.create_index('idx_sumo_edge_metrics_run', 'sumo_edge_metrics', ['run_id'])
    op.create_index('idx_sumo_edge_metrics_edge', 'sumo_edge_metrics', ['sumo_edge_db_id'])


def downgrade() -> None:
    op.drop_index('idx_sumo_edge_metrics_edge', table_name='sumo_edge_metrics')
    op.drop_index('idx_sumo_edge_metrics_run', table_name='sumo_edge_metrics')
    op.drop_index('idx_sumo_edges_network_edge', table_name='sumo_edges')
    op.drop_index('idx_ai_insights_type_time', table_name='ai_insights')
    op.drop_index('idx_anomalies_status', table_name='traffic_anomalies')
    op.drop_index('idx_anomalies_time', table_name='traffic_anomalies')
    op.drop_index('idx_events_time', table_name='local_events')
    op.drop_index('idx_weather_time', table_name='weather_snapshots')
    op.drop_index('idx_incidents_active', table_name='traffic_incidents')
    op.drop_index('idx_flow_probe_time', table_name='traffic_flow_observations')
    op.drop_index('idx_flow_observed_at', table_name='traffic_flow_observations')
    op.drop_index('idx_probe_points_active', table_name='probe_points')
    op.drop_index('idx_road_segments_provider_key', table_name='road_segments')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sumo_scenario_comparisons')
    op.drop_table('alerts')
    op.drop_table('sumo_run_metrics')
    op.drop_table('sumo_edge_metrics')
    op.drop_table('ai_insights')
    op.drop_table('traffic_flow_observations')
    op.drop_table('traffic_anomalies')
    op.drop_table('tomtom_sumo_edge_mappings')
    op.drop_table('sumo_simulation_runs')
    op.drop_table('sumo_scenarios')
    op.drop_table('sumo_edges')
    op.drop_table('probe_points')
    op.drop_table('weather_snapshots')
    op.drop_table('traffic_incidents')
    op.drop_table('sumo_networks')
    op.drop_table('road_segments')
    op.drop_table('local_events')
    op.drop_table('citizen_reports')
    op.drop_table('areas_of_interest')
    op.drop_table('app_users')
    op.drop_table('alert_channels')
    # ### end Alembic commands ###
